### ISSUE TITLE
Disable rubber band effect

### ISSUE THREAD

**Issue by Keith94** [ExOptsTeam/NFSMWExOpts#16]
The game seems to have catch up (rubber band) AI, according to [here](https://www.nfsunlimited.net/forum/viewtopic.php?p=229832#p229832). Is it possible to add that fix here?

**Comment by nlgzrgn** [comment]
Shhh, be quiet and stay tuned. ;)

**Comment by vjadid** [comment]
@nlgzrgn Can you please declare/confirm that rubber banding can be disabled by NFSMWExOpts so that I can put your comment as citation on PCGW [here](https://pcgamingwiki.com/wiki/Need_for_Speed:_Most_Wanted#Disable_AI_catch-up_.28rubber_band_effect.29)
