### ISSUE TITLE
Unlock All Things doesn't unlock all things

### ISSUE THREAD

**Issue by AleksandarColovic** [ExOptsTeam/NFSMWExOpts#26]
When you use any of the "Unlock All Things" options (both the hotkey switch and the setting in the ini) the parts you get after beating Razor are not unlocked. Can this be fixed?

Also 2 suggestions:
1) Add options that allow you to add all of the bonus/cop cars to career
2) Add an option to buy the Unique Performance Upgrades in the shop, like you can in the "My Cars" customization in the main menu

**Comment by AeroWidescreen** [comment]
> When you use any of the "Unlock All Things" options (both the hotkey switch and the setting in the ini) the parts you get after beating Razor are not unlocked. Can this be fixed?

It actually does unlock those parts, but they remain hidden until you complete the game. A feature that unhides these parts should be coming to the next release of ExOpts. If you don't want to wait then I could tell you how to do it through Cheat Engine or by hex editing.

**Comment by AleksandarColovic** [comment]
> It actually does unlock those parts, but they remain hidden until you complete the game. A feature that unhides these parts should be coming to the next release of ExOpts. If you don't want to wait then I could tell you how to do it through Cheat Engine or by hex editing.

Well thanks for the reply, but I don't need it right now, I'll wait for the next release.
I already have a temporary solution, it just takes too long. Tho' Hex editing takes even longer... :smile: 

My solution is: 
I open up the marker editor and add the markers I need. 
For example I add a rim marker, 
then I load the save with that rim marker,
then I go to the shop, 
then I press the hotkey to unlock all things,
then I use the marker and viola ... The Lowenhart BR5 (unlocked by beating Razor) is there.
I get the rims and disable the unlocks again with the hotkey.

Simple, tho takes a bit of time. Having a simple option is way faster :smile:

**Comment by nlgzrgn** [comment]
You can use new ShowMoreCustomizationOptions feature came with v7.0.1.1337, which solves that problem.
