### ISSUE TITLE
Rebinding keys doesn't work.

### ISSUE THREAD

**Issue by clya900** [ExOptsTeam/NFSMWExOpts#28]
I tried changing the config in the Extra Options, so I could disable the hotkeys that change certain settings, but when I did so, the hotkeys still would activate when I pressed on the default keys; this also happens if I try to reassign them to different keys. Is there a way to fix this? I'm sure it's a very simple fix. Thanks!

**Comment by nlgzrgn** [comment]
Hi! Looks like your game is installed into a restricted directory.
Try these:
1) Run your game as administrator.
2) Take ownership of your game folder.
3) Move the whole installation to somewhere else on your PC. (D:\Games for example)

**Comment by clya900** [comment]
I tried it, but even though the config file was saved, the options would still would activate if I pressed the default keys. Anyway, to replicate this problem, just change some key bindings in the config file in an unrestricted directory, save the file and re-open it to make sure that it was saved properly, then run the game afterwards; you should notice that the key bindings remain the same as earlier. Also, make sure the game is in an unrestricted directory too.

**Comment by clya900** [comment]
UPDATE: It appears to only happen for the headlights option, but not others.

**Comment by berkay2578** [comment]
@nlgzrgn 
https://github.com/ExOptsTeam/NFSMWExOpts/blob/master/NFSMWExtraOptions/dllmain.cpp#L925
`hotkeyToggleHeadLights = iniReader.ReadInteger("Hotkeys", "HeadLights", 72); // H`
The release ini has it written "Headlights", it's case-sensitive.

**Comment by nlgzrgn** [comment]
Issue is solved with v7.0.1.1339, which can be downloaded from releases section.

**Comment by clya900** [comment]
Thanks!
