### ISSUE TITLE
Issue with ShowMoreCustomizationOptions

### ISSUE THREAD

**Issue by NicolasFLM** [ExOptsTeam/NFSMWExOpts#30]
when i have ShowMoreCustomizationOptions enabled, the body kit 5 become unavailable, it looks like the part of the code that show the backroom parts is responsible by this issue. sorry for my bad english.
![pic](https://user-images.githubusercontent.com/26664934/38469949-e12d97de-3b32-11e8-82bb-d6b6d808fd78.png)

**Comment by nlgzrgn** [comment]
Workaround: Disable ShowMoreCustomizationOptions.
