### ISSUE TITLE
Bugged roadside objects in v7.0.1

### ISSUE THREAD

**Issue by SerpensSolidus** [ExOptsTeam/NFSMWExOpts#34]
In the latest version (v7.0.1.1339), a lot of roadside objects (signs, lampposts etc.) don't slow you down anymore when you crash into them. You can also drive straight through the concrete gas station pillars.
![nfsmw002](https://user-images.githubusercontent.com/12694967/39845748-f04fa33c-53f7-11e8-9a26-2ac52ed12bd7.png)

**Comment by nlgzrgn** [comment]
The reason is Infinite Collision Mass Fix.
Workaround: Disable it from the ini file.
(v8.0.0.1337 disables it by default)
