### ISSUE TITLE
Unknown branch breaks Body kits

### ISSUE THREAD

**Issue by InSovietCS** [ExOptsTeam/NFSMWExOpts#35]
An unknown branch of code in the INI file makes body kits 3 and 4 go missing. Removing the extra options file fixes the issue. Resetting the extra options file to the default does not fix the issues.

+Edit: ASI file breaks the body kits, not the INI file.

**Comment by InSovietCS** [comment]
+Adding the fact that creating more accounts lessens this number to only two bodykits that are avail (body kit 3 starts missing too)

**Comment by nlgzrgn** [comment]
Closed. Dupe of #30
