### ISSUE TITLE
Removing mod prevents savegame from loading

### ISSUE THREAD

**Issue by Keith94** [ExOptsTeam/NFSMWExOpts#44]
![nvidia_share_2019-01-09_00-56-49](https://user-images.githubusercontent.com/5490615/50888181-ef7f2a00-13a9-11e9-98c1-41c7aec1d293.png)

**Comment by feel-the-dz3n** [comment]
That's not weird at all, because NFSMWExOpts actually hacks the game and avoids all secured parts.

**Comment by mysteriously** [comment]
Good to know after using it. I have a backup of course. However please find solution for this as people time can get wasted in case of willingness to come back to original state
