### ISSUE TITLE
Strange vehicles are automatically unlocked with default settings

### ISSUE THREAD

**Issue by Keith94** [ExOptsTeam/NFSMWExOpts#45]
![speed_2019-01-11_10-51-00](https://user-images.githubusercontent.com/5490615/51053582-e8fdd780-158e-11e9-9ad3-5e6499266807.jpg)

This isn't a game feature, but an ExOpts feature, right?

**Comment by feel-the-dz3n** [comment]
Of course

**Comment by Keith94** [comment]
Shouldn't they not be, then?
