### ISSUE TITLE
[Misc] Grammar issues in the README

### ISSUE THREAD

**Issue by haru7703** [ExOptsTeam/NFSMWExOpts#5]
Various small grammar issues in the readme. While not a big deal it will help users understand the readme better.

**Comment by nlgzrgn** [comment]
Oh! Sorry for that.
English isn't my native language, and I kinda rushed that read me. If you can help me fix these issues, I'll be very happy. :)

**Comment by linuxfanatic1** [comment]
Sure :) I'll send you the fixed readme through skype when i'm done.
