### ISSUE TITLE
problem on windows xp

### ISSUE THREAD

**Issue by PewingPerson** [ExOptsTeam/NFSMWExOpts#61]
whenever i try to launch the game this happens
file:///C:/Documents%20and%20Settings/DAVE/My%20Documents/Lightshot/Screenshot_2.png

**Comment by dimaspaf14** [comment]
>  file:///C:/Documents%20and%20Settings/DAVE/My%20Documents/Lightshot/Screenshot_2.png

It doesnt seem like an image for me, its just a code Or file that you opened with your browser

**Comment by dimaspaf14** [comment]
My problem already opened here, the game wont run on windows xp sp3, something is missing, im gonna take a screenshot later..

**Comment by nlgxzef** [comment]
Extra Options doesn't support Windows XP. But, you can try using an ASI loader, which is modified to provide XP support. If it still doesn't work, we have nothing else to do.

Link: https://github.com/xan1242/Ultimate-ASI-Loader/releases

Closed.

**Comment by Budiawan69** [comment]
> Extra Options doesn't support Windows XP. But, you can try using an ASI loader, which is modified to provide XP support. If it still doesn't work, we have nothing else to do.
> 
> Link: https://github.com/xan1242/Ultimate-ASI-Loader/releases
> 
> Closed.

Ok, its works on my windows xp, thank you so much

**Comment by dimaspaf14** [comment]
> Extra Options doesn't support Windows XP. But, you can try using an ASI loader, which is modified to provide XP support. If it still doesn't work, we have nothing else to do.
> 
> Link: https://github.com/xan1242/Ultimate-ASI-Loader/releases
> 
> Closed.

Ok, its works very well, thank you soo much
